name: Android

on:
  push:
    branches:
      - main
      - release
      - rc/**

jobs:
  build-android:
    name: build-android
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Run build script
        run: |
          cd build/android && printf "y" | ./build.sh continuous
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: filament-android
          path: out/filament-android-release.aar
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: filamat-android-full
          path: out/filamat-android-release.aar
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: filamat-android-lite
          path: out/filamat-android-lite-release.aar
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: gltfio-android-release
          path: out/gltfio-android-release.aar
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: gltfio-android-lite-release
          path: out/gltfio-android-lite-release.aar
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: filament-utils-android-release
          path: out/filament-utils-android-release.aar
