name: Npm Deploy

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to deploy (e.g., v1.42.2)'
        required: true
        default: 'v1.42.2'

jobs:
  npm-deploy:
    name: npm-deploy
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.event.inputs.release_tag }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run build script
        run: |
          cd build/web && printf "y" | ./build.sh release
      - name: Deploy to npm
        run: |
          cd out/cmake-webgl-release/web/filament-js
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

